In [1]:
import torch
import numpy as np
import torch.nn as nn


### Part 1. Pytorch Tutorial for Beginners


---

#### 1. torch.Tensor

---


In [2]:
uniform_tensor = torch.rand(3, 3)
normal_tensor = torch.randn(3, 3)
uniform_tensor, normal_tensor

(tensor([[0.7731, 0.2637, 0.7758],
         [0.6063, 0.7716, 0.1953],
         [0.0136, 0.2960, 0.2343]]),
 tensor([[-1.3556, -1.0657, -0.6509],
         [-0.2942, -0.1041,  0.6442],
         [ 0.5948,  1.4590, -1.9966]]))

In [3]:
ones_tensor = torch.ones(3, 3)
zeros_tensor = torch.zeros(3, 3)
ones_tensor, zeros_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [4]:
identity_tensor = torch.eye(3, 3)
identity_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [5]:
tensor_from_array = torch.from_numpy(np.random.randn(3, 3))
tensor_from_array

tensor([[-1.6729,  0.5461,  1.2310],
        [-0.3466, -0.1412,  0.0225],
        [ 1.4155, -0.0139, -0.8034]], dtype=torch.float64)

---

#### 2. matrix multiplication

---


In [6]:
matrix_multiplication = mul = torch.mm(uniform_tensor, normal_tensor)
element_wise = uniform_tensor * normal_tensor
matrix_multiplication, element_wise


(tensor([[-0.6641,  0.2805, -1.8823],
         [-0.9327, -0.4415, -0.2876],
         [ 0.0339,  0.2965, -0.2859]]),
 tensor([[-1.0480, -0.2810, -0.5049],
         [-0.1784, -0.0803,  0.1258],
         [ 0.0081,  0.4319, -0.4678]]))

---

#### 3. differentiation (AutoGrad)

---


In [7]:
x1 = torch.tensor([2.0], requires_grad=True)
x2 = torch.tensor([2.0], requires_grad=True)
x3 = torch.tensor([2.0], requires_grad=True)
z1 = x1
z2 = x2**2
z3 = x3**3

In [8]:
z1.backward()
z2.backward()
z3.backward()


In [9]:
print(f"dz1/dx1 evaluated in {x1.item()}: {x1.grad.item()}")  # dz1/dx = 2
print(f"dz2/dx2 evaluated in {x2.item()}: {x2.grad.item()}")  # dz2/dx = 2 * 2
print(f"dz3/dx3 evaluated in {x3.item()}: {x3.grad.item()}")  # dz3/dx = 3 * 4

dz1/dx1 evaluated in 2.0: 1.0
dz2/dx2 evaluated in 2.0: 4.0
dz3/dx3 evaluated in 2.0: 12.0


---

#### 4. neural network

---


In [10]:
input_layers = 10
hidden_layers = 20
output_layers = 5


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_layers, hidden_layers)
        self.fc2 = nn.Linear(hidden_layers, hidden_layers)
        self.out = nn.Linear(hidden_layers, output_layers)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        return x


In [11]:
input = torch.randn(10)
net = Net()
output = net(input)
input, output


(tensor([-0.1469, -1.4569,  0.2845, -0.9110,  0.7376,  0.3580,  2.0266, -0.5681,
          1.1883, -0.8960]),
 tensor([-0.2467, -0.0319,  0.1419,  0.1633, -0.2286], grad_fn=<AddBackward0>))